tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/php'

# Make sure apps get installed in system Applications dir
cask_args appdir: '/Applications'

brew 'git', args: ['without-completions']
brew 'tree'
brew 'node'
brew 'trash'
brew 'wget'

brew 'autoconf'
brew 'automake'
brew 'git', args: ['without-completions']
brew 'openssl'
brew 'phantomjs'
brew 'casperjs'
brew 'pcre2'
brew 'fish'
brew 'libpng'
brew 'freetype'
brew 'gdbm'
brew 'gettext'
brew 'git-flow'
brew 'gnu-getopt'
brew 'gnupg'
brew 'htop-osx'
brew 'icu4c'
brew 'jpeg'
brew 'libtool'
brew 'xz'
brew 'imagemagick'
brew 'libevent'
brew 'libxml2', args: ['with-python']
brew 'makedepend'
brew 'msgpack'
brew 'pwgen'
brew 'pass'
brew 'pcre'
brew 'swig'
brew 'tmux'
brew 'tokyo-cabinet'
brew 'wifi-password'
brew 'zsh', args: ['without-etcdir']

cask 'alfred'
cask 'firefox'
cask 'google-chrome'
cask 'iterm2'
cask 'sequel-pro'
cask 'skype'
cask 'slack'
cask 'spotify'
cask 'sublime-text3'
cask 'vagrant'
cask 'vlc'
